export default {
  ER_USERNAME: '请输入用户名',
  ER_SIGNIN_USERNAME: '请输入用户名',
  ER_SIGNIN_PASSWORD: '请输入密码',
  ER_SLIDING_CAPTCHA: '请进行滑动验证',
  ER_CELLPHONE_EMPTY: '请输入手机号码',
  ER_CELLPHONE: '手机号码格式不正确',
  ER_VERIFICATION_EMPTY: '请输入手机验证码',
  ER_CREW_STAFF_EMPTY: '请输入员工编号',
  ER_CREW_STAFF: '员工编号格式不正确，应包含英文和数字，长度为2-10位',
  ER_REALNAME_EMPTY: '请输入员工姓名',
  ER_REALNAME: '员工姓名格式不正确，应包含汉字、英文和数字，长度为2-10位',
  ER_OLD_PASSWORD_EMPTY: '请输入原密码',
  ER_OLD_PASSWORD: '原密码校验错误',
  ER_PASSWORD_EMPTY: '请输入密码',
  ER_PASSWORD: '密码格式不正确，必须包含英文和数字，长度为6-30位',
  ER_RE_PASSWORD_EMPTY: '请输入确认密码',
  ER_RE_PASSWORD: '确认密码与新密码不一致',
  IMAGE_FORMAT: '上传头像图片只能是 JPG、PNG、GIF 格式',
  IMAGE_SIZE: '上传头像图片大小不能超过2MB',
  ER_USERGROUP_EMPTY: '请选择所属银行机构',
  ER_QUESTION_EMPTY: '请输入问题',
  ER_ANSWER_EMPTY: '请输入答案',
  ER_UPDATETIME_EMPTY: '请选择时间',
  ER_LOAN_AMOUNT_MIN_EMPTY: '请输入贷款最低额度',
  ER_LOAN_AMOUNT_MIN_FORMAT: '贷款最低额度格式不正确',
  ER_LOAN_AMOUNT_MAX_EMPTY: '请输入贷款贷款最高额度',
  ER_LOAN_AMOUNT_MAX_FORMAT: '贷款最高额度格式不正确',
  ER_LOAN_AMOUNT_MAX_RANGE: '最高贷款额度大于最小额度'
}
