export default {
  USERNAME_PLACEHOLDER: '请输入用户名',
  PASSWORD_PLACEHOLDER: '请输入用户名',
  THEME_HAS_BEEN_CHANGED: '主题更换成功',
  VERIFICATION_TIPS_USERNAME: '请输入用户名',
  VERIFICATION_TIPS_INTRODUCTION: '请输入用户描述',
  VERIFICATION_TIPS_CELLPHONE: '请输入手机号码',
  VERIFICATION_TIPS_ROLESNAME: '请输入用户角色',
  VERIFICATION_TIPS_USERGROUP: '请输入用户所属单位',
  VERIFICATION_TIPS_CARDID: '请输入身份证',
  VERIFICATION_TIPS_STATUS: '请输入状态',
  VERIFICATION_TIPS_CREATETIME: '请输入创建时间',
  UPDATE_SUCCESS_TITLE: '更新',
  UPDATE_SUCCESS_MESSAGE: '用户信息更新成功',
  SEND_MESSAGE: '短信已发送',
  SUCCESSFUL_OPERATION: '操作成功'
}
